---
- name: /etc/hosts is up to date
  hosts: 192.168.56.108
  become: true
  tasks:
    - name: master in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '192.168.56.108 master'
        state: present
