---
- name: Redhat in keyword
  hosts: 192.168.56.108
  gather_facts: yes
  become: yes
  vars:
    supported_distros:
      - CentOS
      - Redhat
      - Fedora
  tasks:
    - name: stopped mariadb using service, where supported
      service:
        name: mariadb
        state: stopped
      when: ansible_distribution in supported_distros      
