---
- name: boolean test
  hosts: 192.168.56.108
  become: true
  vars:
    run_my_task: true
  tasks:
    - name: mariadb is stopped
      service:
        name: mariadb
        state: stopped
      when: "{{ run_my_task }}"

