---
- name: boolean test
  hosts: 192.168.56.108
  become: true
  vars:
    my_service: mariadb
  tasks:
    - name: mariadb is started
      service:
        name: mariadb
        state: started
      when: my_service is defined

