---
- name: httpd and mariadb are running
  hosts: 192.168.56.108
  vars:
    web_db:
      - httpd
      - mariadb
  tasks:
    - service:
        name: "{{ item }}"
        state: started
      loop: "{{ web_db }}"

