---
- name: Render Jinja loop test
  hosts: 192.168.56.108
  gather_facts: no
  tasks:
    - name: Render jinja template
      template:
        src: jinja-loop.j2
        dest: rendered_template.txt
      vars:
        my_list:
          - apple
          - samsung
          - lg
          - skt
