---
- name: jinja test
  hosts: 192.168.56.108
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Render jinja template
      template:
        src: template.j2
        dest: rendered_template.txt
