---
- name: Install and restart the web server
  hosts: 192.168.56.108
  become: yes
  tasks:
    - name: Install Web Server
      yum:
        name: httpd
        state: latest

    - name: Restart Web Server
      service:
        name: httpd
        state: restarted
