---
- name: handler example
  hosts: 192.168.56.108
  tasks:
    - name: check handler
      command: echo "Your tasks are completed"
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
  
