---
- name: Latest version of notapkg is installed
  hosts:  192.168.56.108
  become: yes
  yum:
    name: notapkg
    state: latest

- name: Latest version of gnutls is installed
  become: yes
  hosts: 192.168.56.108
  yum:
    name: gnutls
    state: latest

